name: Unreal Actions Collection
description: Run actions for unreal plugins to improve code review experience and CI/CD.
author: brumenn
inputs:
  root:
    description: Plugin root directory.
    required: false
    default: .
  engine_version:
    description: Engine version to use.
    required: false
    default: 5.5
  target:
    description: target location to deploy.
    required: false
    default: .
runs:
  using: "composite"
  steps:

    - name: Deploy plugin build
      run: |
          sh ./DeployPluginBuild.sh
