name: Deploy unreal plugin

on:
  workflow_call:

jobs:
  deploy-unreal-plugin:
    name: Deploy unreal plugin
    runs-on: self-hosted
    env:
      PROD_UE_PLUGINS_PATH: ${{ secrets.PROD_UE_PLUGINS_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name : Checkout reusable workflow repository
        uses: actions/checkout@v4
        with:
          repository: androidsassocies/.gha
          path: .gha

      - name: Where bash
        shell: cmd
        run : |
          where bash
          where git

      - name: Make the script files executable
        shell: cmd
        run: powershell -Command "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process -Force"

      - name: Deploy plugin build
        # Pay attention to the target path, '\\' gives '\',
        # so to get a real '\\' write '\\\\' or use '/' instead of '\'.
        # (e.g '\\\\10.20.19.152\Shared\MyPlugins' or '//10.20.19.152/Shared/MyPlugins')
        #shell: "C:/Program Files/Git/bin/bash.exe"
        shell: cmd
        run: |
          "C:/Program Files/Git/bin/bash.exe" ./.gha/deploy_plugin_build.sh -r ${{ github.workspace }} -t $env:PROD_UE_PLUGINS_PATH -v 5.5 -c
