name: Deploy unreal plugin

on:
  workflow_call:

jobs:
  deploy-unreal-plugin:
    name: Deploy unreal plugin
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy plugin build
        uses: androidsassocies/.gha/.github/actions/unreal@main
        with:
          engine_version: 5.5
